### ISSUE TITLE
BACK - Montar estrutura de tabelas CNAB (FASE III)

### ISSUE THREAD

**Issue by yxuo** [RJ-SMTR/api-cct#162]
## Depende de:
- #153
- #187

## Objetivo

Após termos o dicionário montado, a estrutura de tabelas desehada e o gerador de remessa montado, 
iremos criar esses tabelas.

## Tarefas

- [ ] Criar tabelas
- [ ] Criar rotinas:
 - Puxar dados das tabelas de inserção de dados e criar remessa
 - Salvar remessa criada na tabela CNAB

**Comment by BernardoMarcos** [comment]
## Situação

**_PRÓXIMO PASSOS:_**
- Aguardar a reunião de entendimento com a CEF (provavelmente ocorrerá nesta semana 15/01 a 19/01)
- Após a reunião com a CEF, será marcada a reunião com o time de dados para alinhar as expectativas.

**Comment by yxuo** [comment]
## Lógica de negócio

- A tabela ClienteFavorecido terá dados para clientes tanto da view fase 4 quanto a view Transacoes.
- Transacao aponta (FK) para a tabela Pagador
- TransacaoClienteItem é uma tabela associativa entre Transacao e ClienteItemFavorecido

**Comment by yxuo** [comment]
## Diagrama de Referência 

![Image](https://github.com/RJ-SMTR/api-cct/assets/54970870/c0637dd4-4d45-4faa-bb8d-a8703823bc68)

**Comment by yxuo** [comment]
### Listener transacao
-. Criar JobListenerTransacao

Esse job deve fazer:
1. Pegar da view BRT e inserir dados do ClienteFavorecido
2. xxx

###
