### ISSUE TITLE
BACK - Lançamentos Financeiros (FASE IV)

### ISSUE THREAD

**Issue by rivailruiz** [RJ-SMTR/api-cct#195]
**FORM1 - Insert de Dados** 
Tela de entrada de dados. Uma vez os dados armazenados em arquivo de banco esse FORM servirá para: Escrever, Alterar, Excluir e Consultar.
----------------------------------------------------------------------------------------------//
_Campo Favorecido -_ Campo de Seleção composto por registros de 4 consórcios e 1 BRT (Deverá ser armazenado no banco para seleção);
_Campo Mês -_ Campo de Seleção (descrição do mês);
_Campo Período -_ Campo que vai compor duas quinzenas: 1a Quinzena de 01 a 15; 2a Quinzena de 16 a 31 (para mês com 31 dias);
_Campo Data Ordem de Pagamento_ - Campo para digitar a data de ordem de pagamento - Data que definirá o pagamento para os favorecidos.
_Campo N° do Processo_ Campo que será digitado informando o número do processo ao favorecido selecionado, mês e período.
----------------------------------------------------------------------------------------------//
_Campo Algoritmo_ - Campo que será lançado o valor total em moeda real (R$);
_Campo Glosa -_ Campo que será lançado o valor da glosa (refere-se a penalidade de algum indicador). Caso tenha mais de uma glosa, será somado e lançado o valor total da glosa. Valor em moeda real (R$);
_Campo Recurso -_ Campo que será lançado o valor do recurso e que se refere um valor justificado pela empresa para o pagamento devido ou indevido, conforme a análise da Prefeitura. Para valores indevido, o valor será formato com o sinal negativo (-) e na cor vermelha. Valor em moeda real (R$);
_Campo Valor à pagar -_ Campo que será calculado conforme os lançamentos anteriores. Valor em moeda real (R$); 

![Image](https://github.com/RJ-SMTR/api-cct/assets/144030598/d239bb04-bd00-4899-819e-0cdbbd691777)
###############################################################################################

**FORM2 - Alçada de Aprovação**
Tela de visualização dos lançamentos financeiros e para aprovação e liberação para pagamento
----------------------------------------------------------------------------------------------//
_Campo Saldo do Banco -_ Será apresentado o saldo atual com a baixa do arquivo retorno para apoio e tomada de decisão sobre os lançamentos registrados no período selecionado.
_Campo Valor Autorizado -_ Contempla a soma de todos os lançamentos (Grid de Favorecidos), e que foram autorizados pelos aprovadores - máximo de 2 aprovadores;
_Campo Mês -_ Campo de seleção com o descritivo do mês;
_Campo Período -_ Campo que vai compor duas quinzenas: 1a Quinzena de 01 a 15; 2a Quinzena de 16 a 31 (para mês com 31 dias);
_Campo Novo - Campo de apoio para criar um novo registro leva-o a uma nova tela de lançamentos _financeiros;_
_Campo Favorecido - Contempla todos os lançamentos referente aos consórcios registrados dentro do mês e período selecionado contemplando as _colunas:_
_Consórcios/BRT - Lista as empresas que foram registradas na tela de lançamento financeiros;
_Valor à pagar - Define o valor a ser pago para a empresa calculando Vlr do Algoritmo - Vlr Glosa + ou - Vlr Recursos indeferidos ou deferidos;_
 _Lançados por - Responsável pelo lançamento - padrão Nome e Último;_
_Data Ordem de Pagto - Campo que define a data de ordem de pagto;_
 _Autorizado por - Responsável pela autorização e liberação para pagamento. - padrão Nome e Último;_ 
       _Regra_ I) 1ª aprovação mostra o nome do 1° aprovador e o botão Autorizar permanece na cor _AZUL;_
       _Regra_ II) 2ª aprovação mostra o nome do 2° aprovador, do lado do 1° aprovador, e o botão Autorizado na cor _VERDE._
_Botão Autoriza/Autorizado/Vencido -_ Botões de controle que define a tomada de decisão para aprovação de pagamento._
      _Regra_ I) Botão Autoriza (Cor Azul), Botão de seleção para aprovar ou não. A não aprovação mantem-se inalterado.
      _Regra_ II) Botão Autorizado (Cor Verde), Segue a alçada para duas aprovações, e como regra, a 2ª aprovação é que vale para a 
                       mudança de status do Botão na cor e _nome;_
-Ícone da Lixeira e Lápis -_ A lixeira servirá para excluir a linha do favorecido e o lápis para editá-lo o levando para a tela de lançamentos financeiros para ajustes dos campos _correspondentes;_
_Campo Total - Somatório de todos os valores na coluna Valor à _pagar._ 

![Image](https://github.com/RJ-SMTR/api-cct/assets/144030598/acd66f26-f8fe-4b54-8ba4-7121091f60cb)
###############################################################################################
FORM3 - Aprovação
Tela de aprovação que será conduzida pelo Aprovador para visualizar os dados de cada favorecido para a liberação de pagamento.
----------------------------------------------------------------------------------------------//
Os campos compostos neste FORM3 são idênticos ao do FORM1; 
_Botão Autorizado - Botão que define a alçada de aprovação de pagamento. **_O STATUS do Botão Autorizado só será modificado mediante a 2ª aprovação. A 1ª aprovação será confirma, mas não mudará o STATUS e a COR do botão. Vale lembrar que o nome do 1° e 2° aprovador vão aparecer na coluna Autorizado por na sequencia da aprovação;_
_Botão Retornar -_ Suspende o processo de aprovação e retorna ao FORM2 mantendo seus dados inalterados para uma posição mudança ou ajuste (conforme tomada de decisão da diretoria). 

![Image](https://github.com/RJ-SMTR/api-cct/assets/144030598/4bc1a940-d3d7-4c9c-bd4a-69ee8161d761)

**Comment by rivailruiz** [comment]
TODO: 

1- pegar dados do favorecido com o william
2- acertar os campos do form

**Comment by BernardoMarcos** [comment]
![Image](https://github.com/RJ-SMTR/api-cct/assets/144030598/34e2e542-8d66-4b6b-bcdd-5c5c75673251)
![Image](https://github.com/RJ-SMTR/api-cct/assets/144030598/66cecb74-805c-4928-a8f5-ec5ce8937699)
